{% set version = "1.2.0" %}

package:
  name: language-tags
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/l/language-tags/language_tags-{{ version }}.tar.gz
  sha256: e934acba3e3dc85f867703eca421847a9ab7b7679b11b5d5cfd096febbf8bde6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - python >=2.7

test:
  imports:
    - language_tags
    - language_tags.data
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/OnroerendErfgoed/language-tags
  summary: This project is a Python version of the language-tags Javascript project.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
