{% set version = "1.2.0" %}

package:
  name: language-tags
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/l/language-tags/language_tags-{{ version }}.tar.gz
  sha256: e934acba3e3dc85f867703eca421847a9ab7b7679b11b5d5cfd096febbf8bde6

build:
  number: 1
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - language_tags
    - language_tags.data
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/OnroerendErfgoed/language-tags
  summary: This project is a Python version of the language-tags Javascript project.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
