{% set name = "language-tags" %}
{% set version = "1.2.0" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace("-", "_") }}-{{ version }}.tar.gz
    sha256: e934acba3e3dc85f867703eca421847a9ab7b7679b11b5d5cfd096febbf8bde6
  # TODO: upstream PR
  - url: https://raw.githubusercontent.com/OnroerendErfgoed/{{ name }}/{{ version }}/LICENSE
    sha256: 9e07b99a50ee9d0b3bba384236a34763dbb85b555919bf0d20b4c4b37cc715aa

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - python >=2.7
    - six

test:
  imports:
    - language_tags
    - language_tags.data
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/OnroerendErfgoed/language-tags
  summary: This project is a Python version of the language-tags Javascript project.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
